SWM-OneStep/backend

todos/views.py
- **Jira Ticket**:
<br/>
api 를 아래 수정사항 맞춰 수정하였습니다
- api 에서 post를 하는 경우 id 만 주는 api 에서 객체를 반환하도록 수정
- delete 된 객체도 보이는 문제 수정
- todo 객체 생성시 start_date 와 end_date 검증 과정 추가
</br>
| 기능 | 스크린샷 |
| --- | --- |
| gif |  |
<br/>
<br/>
=> fix : API 수정사항 반영

todos/serializers.py, todos/swagger_serializers.py, todos/views.py
- **Jira Ticket**: sz-199
https://swm-safezone.atlassian.net/browse/SZ-199?atlOrigin=eyJpIjoiMTg3NWY0MDMyNjMxNDlkZmFhMDA2ODNhZjk1MzI5NWUiLCJwIjoiaiJ9
<br/>
swagger 적용했습니다!
- 
</br>
| 기능 | 스크린샷 |
| --- | --- |
| gif | <img width="1486" alt="image" src="https://github.com/user-attachments/assets/c4be5b4a-03ed-404c-b497-b4064753b908"> |
<br/>
<br/>
=> [SZ-199] feat: swagger 적용

.github/workflows/deploy_to_ecs.yml
- **Jira Ticket**: SZ-109
<br/>
한 줄 소개
- 상세 소개
- 
</br>
| 기능 | 스크린샷 |
| --- | --- |
| gif |  |
<br/>
=> [SZ-109] (trials) Update deploy_to_ecs.yml

.github/workflows/deploy_to_ecs.yml
- **Jira Ticket**:
<br/>
한 줄 소개
- 상세 소개
- 
</br>
| 기능 | 스크린샷 |
| --- | --- |
| gif |  |
<br/>
=> [SZ-109] (trial) Update deploy_to_ecs.yml

accounts/views.py, ecs-task-def.json, onestep_be/settings.py
- **Jira Ticket**: SZ-109
<br/>
한 줄 소개
- ECS 태스크 정의 정보가 담긴 ecs-task-def.json 파일 추가
</br>
| 기능 | 스크린샷 |
| --- | --- |
| gif |  |
<br/>
=> [SZ-109] CI/CD를 위해 ECR ECS 설정하기

.github/workflows/deploy_to_ecs.yml, accounts/views.py, ecs-task-def.json, onestep_be/settings.py
- **Jira Ticket**: SZ-109
<br/>
한 줄 소개
- 상세 소개
- 
</br>
| 기능 | 스크린샷 |
| --- | --- |
| gif |  |
<br/>
=> [SZ-109] ECS task definition json 파일 추가 및 DB_HOST 값 변경

todos/admin.py, todos/swagger_serializers.py, todos/tests/test_subtodo.py, todos/views.py
- **Jira Ticket**:[SZ-217](https://swm-safezone.atlassian.net/browse/SZ-217?atlOrigin=eyJpIjoiOTNmN2EyYmYwOTQ4NDkxNDhjYTdhNzY3OTVjZjU2MjQiLCJwIjoiaiJ9)
<br/>
자잘한 버그들 수정했습니다.
- chatgpt 사용자가 사용하는 content 언어에 따라 변화할 수 있도록 할 것
- todo 및 subtodo order 만 바꾸는 것도 수정되도록 fix (완) 
- 주석 처리 삭제 (완)
</br>
| 기능 | 스크린샷 |
| --- | --- |
| gif |  |
<br/>
<br/>
[SZ-217]: https://swm-safezone.atlassian.net/browse/SZ-217?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [Sz 217] 작은 버그들 수정

.github/workflows/deploy_to_ecs.yml, .github/workflows/deploy_to_ecs_prod.yml
- **Jira Ticket**:[SZ-109](https://swm-safezone.atlassian.net/browse/SZ-109)
[SZ-109]: https://swm-safezone.atlassian.net/browse/SZ-109?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: Dockerfile docker build 옵션에 -f으로 도커파일 경로 명시적으로 설정

Dockerfile.dev, Dockerfile.prod
- **Jira Ticket**: [SZ-109](https://swm-safezone.atlassian.net/browse/SZ-109)
[SZ-109]: https://swm-safezone.atlassian.net/browse/SZ-109?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore: 오타 수정 - settings -> setting

accounts/urls.py, accounts/views.py
- **Jira Ticket**:[SZ-219](https://swm-safezone.atlassian.net/browse/SZ-219?atlOrigin=eyJpIjoiODJlYmQyNTMwN2Q1NDdiZmI5N2ZjNzIwOTA0Yzc4OWMiLCJwIjoiaiJ9)
<br/>
android client id 반환
- aws secret 에 넣어놓고 이를 반환하는 api를 작성했습니다.
- 
</br>
| 기능 | 스크린샷 |
| --- | --- |
| gif |  |
<br/>
<br/>
[SZ-219]: https://swm-safezone.atlassian.net/browse/SZ-219?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [SZ-219] android clint id 반환 api

README.md, accounts/admin.py, accounts/aws.py, accounts/models.py, accounts/serializers.py, accounts/tests.py, accounts/tokens.py, accounts/urls.py, accounts/views.py, pyproject.toml, todos/apps.py, todos/lexorank.py, todos/models.py, todos/tests/test_category.py, todos/tests/test_todo.py, todos/urls.py, todos/views.py
- **Jira Ticket**:[SZ-213](https://swm-safezone.atlassian.net/browse/SZ-213?atlOrigin=eyJpIjoiMmRhMjdjMDJmYmNkNDhjZDhjMGM0NWZmNzc3Njk0MmYiLCJwIjoiaiJ9)
<br/>
Linter 를 모든 파일에 적용하였습니다.
- isAuthentication 으로 todo 를 전부 바꿔줬습니다.
- 
</br>
| 기능 | 스크린샷 |
| --- | --- |
| gif |  |
<br/>
<br/>
=> [Sz-213] Linter 파일 모두 적용 + isAuthentication 적용 

todos/models.py, todos/serializers.py, todos/tests/test_category.py, todos/tests/test_subtodo.py, todos/tests/test_todo.py, todos/utils.py, todos/views.py
- **Jira Ticket**:[SZ-209](https://swm-safezone.atlassian.net/browse/SZ-209?atlOrigin=eyJpIjoiY2M4MTU3MTY3YmI0NDdkNDg0ZDRmZTA4YTk4MGJkNDciLCJwIjoiaiJ9)
<br/>
fat model 적용했습니다..
- validation 관련으로는 serializer 에 validate_ 함수에 넣는 방식으로 작성하였습니다.
- 쿼리문과 같은 동작이 필요한 경우에는 model의 manager 부분에 넣었습니다.
</br>
| 기능 | 스크린샷 |
| --- | --- |
| gif |  |
<br/>
진행사항
get 적용 v
get test v
delete 적용 v
subtodo 적용 v
todo 적용 v
category 적용 v
delete test  v
post 적용 v
post test v
update 적용v
update testv
testcase 모두 작동하도록 수정v 
<br/>
=> [Sz-209] fat model 적용

Dockerfile.dev, Dockerfile.prod, Dockerfile.test
- **Jira Ticket**: [SZ-243](https://swm-safezone.atlassian.net/browse/SZ-243)
<br/>
현재 깃허브 워크플로우에서 에러가 나는 상황이라, 에러의 원인이 gunicorn과 uvicorn을 같이 사용할 때 워커에서 타임아웃이 나는 것이라 추측하고 해당 값을 바꾸어 보았습니다. 해당 값을 테스트하기 위해서는 develop 브랜치에 코드가 반영되어야 하기에 임시로 PR을 올립니다. 
[SZ-243]: https://swm-safezone.atlassian.net/browse/SZ-243?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: gunicorn timeout 시간 변경

Dockerfile.dev, Dockerfile.prod, Dockerfile.test, accounts/views.py
- **Jira Ticket**:[SZ-259](https://swm-safezone.atlassian.net/browse/SZ-259)
<br/>
</br>
[SZ-259]: https://swm-safezone.atlassian.net/browse/SZ-259?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [SZ-259] FE-BE 401 Unauthenticated 에러 수정

render_ecs_task_definition.py
- **Jira Ticket**: [SZ-243](https://swm-safezone.atlassian.net/browse/SZ-243)
<br/>
</br>
[SZ-243]: https://swm-safezone.atlassian.net/browse/SZ-243?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: ecs-task.json -> ecs-task-def.json

Dockerfile.dev, Dockerfile.prod, Dockerfile.test
- **Jira Ticket**: [SZ-243](https://swm-safezone.atlassian.net/browse/SZ-243)
<br/>
</br>
[SZ-243]: https://swm-safezone.atlassian.net/browse/SZ-243?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [SZ-243] API 서버 테스트

.github/workflows/deploy_to_ecs.yml, .github/workflows/deploy_to_ecs_prod.yml
<br/>
한 줄 소개
- 상세 소개
- 
</br>
| 기능 | 스크린샷 |
| --- | --- |
| gif |  |
<br/>
<br/>
=> fix : add commit when version changed in workflow

.github/workflows/deploy_to_ecs.yml, .github/workflows/deploy_to_ecs_test.yml
<br/>
한 줄 소개
- 상세 소개
- 
</br>
| 기능 | 스크린샷 |
| --- | --- |
| gif |  |
<br/>
<br/>
=> fix : workflow yml commit origin to develop

.github/workflows/deploy_to_ecs.yml, .github/workflows/deploy_to_ecs_prod.yml, .github/workflows/deploy_to_ecs_test.yml
<br/>
한 줄 소개
- 상세 소개
- 
</br>
| 기능 | 스크린샷 |
| --- | --- |
| gif |  |
<br/>
<br/>
=> fix : workflow yml add token

.github/workflows/deploy_to_ecs.yml, .github/workflows/deploy_to_ecs_prod.yml, .github/workflows/deploy_to_ecs_test.yml
<br/>
한 줄 소개
- 상세 소개
- 
</br>
| 기능 | 스크린샷 |
| --- | --- |
| gif |  |
<br/>
<br/>
=> fix : add action pat

.github/workflows/deploy_to_ecs.yml, .github/workflows/deploy_to_ecs_prod.yml, .github/workflows/deploy_to_ecs_test.yml
<br/>
한 줄 소개
- 상세 소개
- 
</br>
| 기능 | 스크린샷 |
| --- | --- |
| gif |  |
<br/>
<br/>
=> fix : add git pull

.github/workflows/deploy_to_ecs.yml, .github/workflows/deploy_to_ecs_prod.yml, onestep_be/settings.py
<br/>
한 줄 소개
- 상세 소개
- 
</br>
| 기능 | 스크린샷 |
| --- | --- |
| gif |  |
<br/>
<br/>
=> Sz 297 sentry 연결 및 prod, dev 확인용

.github/workflows/deploy_to_ecs.yml, .github/workflows/deploy_to_ecs_prod.yml, .github/workflows/deploy_to_ecs_test.yml
<br/>
한 줄 소개
- 상세 소개
- 
</br>
| 기능 | 스크린샷 |
| --- | --- |
| gif |  |
<br/>
<br/>
=> fix : fix order in ecs.yml

accounts/admin.py, todos/admin.py
- **Jira Ticket**:[SZ-345](https://swm-safezone.atlassian.net/browse/SZ-345)
<br/>
admin page를 작성하였습니다.
- 상세 소개
- 
</br>
| 기능 | 스크린샷 |
| --- | --- |
| gif |  |
<br/>
<br/>
[SZ-345]: https://swm-safezone.atlassian.net/browse/SZ-345?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [Sz 345] Admin page 생성

accounts/authentication.py
- **Jira Ticket**: [SZ-402](https://swm-safezone.atlassian.net/browse/SZ-402)
<br/>
한 줄 소개
- 상세 소개
- 
</br>
| 기능 | 스크린샷 |
| --- | --- |
| gif |  |
<br/>
<br/>
[SZ-402]: https://swm-safezone.atlassian.net/browse/SZ-402?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [SZ-402] fix: middleware 오류 수정

onestep_be/settings.py
<br/>
한 줄 소개
- 상세 소개
- 
</br>
| 기능 | 스크린샷 |
| --- | --- |
| gif |  |
<br/>
<br/>
=> fix : settings

accounts/authentication.py, conftest.py, onestep_be/setting/test.py, onestep_be/settings.py, requirements.txt, todos/firebase_messaging.py, todos/middleware.py, todos/views.py
- **Jira Ticket**: [SZ-366](https://swm-safezone.atlassian.net/browse/SZ-366)
<br/>
</br>
| 기능 | 스크린샷 |
| --- | --- |
| gif |  |
<br/>
<br/>
[SZ-366]: https://swm-safezone.atlassian.net/browse/SZ-366?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [SZ-366] 알림 보내는 로직 추가

Dockerfile.dev, Dockerfile.prod, Dockerfile.test, todos/views.py
- **Jira Ticket**: [SZ-352](https://swm-safezone.atlassian.net/browse/SZ-352)
<br/>
한 줄 소개
- 상세 소개
- 
</br>
| 기능 | 스크린샷 |
| --- | --- |
| gif |  |
<br/>
<br/>
[SZ-352]: https://swm-safezone.atlassian.net/browse/SZ-352?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [SZ-352] 비동기 뷰로 변경하기

todos/models.py, todos/serializers.py, todos/swagger_serializers.py, todos/views.py
- **Jira Ticket**:[SZ-401](https://swm-safezone.atlassian.net/browse/SZ-401)
<br/>
Swagger 수정 + user_id 를 헤더에서 받아오도록 수정했습니다
</br>
<br/>
[SZ-401]: https://swm-safezone.atlassian.net/browse/SZ-401?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [SZ-401] fix : swagger 수정

conftest.py
- **Jira Ticket**: [SZ-430](https://swm-safezone.atlassian.net/browse/SZ-430)
<br/>
- pytest의 성공을 위해서 force_authenticate의 추가 인자를 넣어주었습니다. 
</br>
[SZ-430]: https://swm-safezone.atlassian.net/browse/SZ-430?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [SZ-430] monkeypatch setattr 수정 및 force_authenticate 인자 추가 (pytest 관련 코드 일부 변경)

accounts/models.py, accounts/tests.py, accounts/views.py, onestep_be/settings.py, requirements.txt
- **Jira Ticket**:[SZ-460](https://swm-safezone.atlassian.net/browse/SZ-460?atlOrigin=eyJpIjoiNGRhZDQwMjY3ZDU0NDI0ZTk0MDBhN2QwMjQzM2M4NzIiLCJwIjoiaiJ9)
<br/>
회원 탈퇴 기능을 구현하였습니다.
- 회원 탈퇴시 deleted_at 에 값을 넣도록 구현
- user get 시 deleted_at 을 통해 탈퇴 여부를 확인후 가져옴 
</br>
[SZ-460]: https://swm-safezone.atlassian.net/browse/SZ-460?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [Sz 460] 회원 탈퇴 기능 구현

accounts/views.py
<br/>
한 줄 소개
- 상세 소개
- 
</br>
| 기능 | 스크린샷 |
| --- | --- |
| gif |  |
<br/>
<br/>
=> fix : ios view 수정

onestep_be/setting/dev.py, onestep_be/setting/prod.py, onestep_be/setting/test.py, pyproject.toml
<br/>
한 줄 소개
- 상세 소개
- 
</br>
| 기능 | 스크린샷 |
| --- | --- |
| gif |  |
<br/>
<br/>
=> fix : import 수정

accounts/views.py
- **Jira Ticket**:[SZ-483](https://swm-safezone.atlassian.net/browse/SZ-483)
<br/>
apple social login 구현했습니다.
- 상세 소개
- 
</br>
[SZ-483]: https://swm-safezone.atlassian.net/browse/SZ-483?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [Sz 483] apple social login 구현

accounts/views.py, conftest.py, onestep_be/settings.py, todos/views.py
- **Jira Ticket**:[SZ-298](https://swm-safezone.atlassian.net/browse/SZ-298)
<br/>
로그인 관련으로 문제를 해결해보았습니다
</br>
[SZ-298]: https://swm-safezone.atlassian.net/browse/SZ-298?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [Sz 298] google 로그인 관련 문제 해결

accounts/admin.py, accounts/models.py
- **Jira Ticket**:[sz-489](https://swm-safezone.atlassian.net/browse/SZ-489)
<br/>
탈퇴한 유저한 유저로 재 등록시 기존의 계정을 사용할 수 있도록 구현하였습니다.
</br>
=> [Sz 489] 탈퇴한 유저로 재등록시 기존의 계정을 사용할 수 있는 기능

.github/workflows/deploy_to_ecs.yml, .github/workflows/deploy_to_ecs_prod.yml, onestep_be/settings.py, requirements.txt
- **Jira Ticket**:[SZ-499](https://swm-safezone.atlassian.net/browse/SZ-499)
<br/>
sentry 관련 오류들을 해결해보았습니다.
- span 문제 : 헬스체크 관련 url 을 모두 무시하도록 설정
- version 문제 : backend/version.txt 에 적도록 yaml 파일 수정
</br>
[SZ-499]: https://swm-safezone.atlassian.net/browse/SZ-499?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [Sz-499] sentry 헬스체크 필터링

.github/workflows/deploy_to_ecs.yml, .github/workflows/deploy_to_ecs_prod.yml, todos/views.py
<br/>
한 줄 소개
- 상세 소개
- 
</br>
| 기능 | 스크린샷 |
| --- | --- |
| gif |  |
<br/>
<br/>
=> fix : ecs 관련 수정

.github/workflows/deploy_to_ecs.yml, .github/workflows/deploy_to_ecs_prod.yml
<br/>
한 줄 소개
- 상세 소개
- 
</br>
| 기능 | 스크린샷 |
| --- | --- |
| gif |  |
<br/>
<br/>
=> feat: add ssh private key

.github/workflows/deploy_to_ecs.yml, .github/workflows/deploy_to_ecs_prod.yml, .github/workflows/deploy_to_ecs_test.yml
<br/>
한 줄 소개
- 상세 소개
- 
</br>
| 기능 | 스크린샷 |
| --- | --- |
| gif |  |
<br/>
<br/>
=> fix : ecs yml add token

onestep_be/settings.py
<br/>
한 줄 소개
- 상세 소개
- 
</br>
| 기능 | 스크린샷 |
| --- | --- |
| gif |  |
<br/>
<br/>
=> fix : version txt

todos/models.py, todos/views.py
<br/>
한 줄 소개
- 상세 소개
- 
</br>
| 기능 | 스크린샷 |
| --- | --- |
| gif |  |
<br/>
<br/>
=> fix : post 저장 안되는 문제 + rank 로직 수정

todos/models.py, todos/tests/test_subtodo_post.py, todos/views.py
<br/>
한 줄 소개
- 상세 소개
- 
</br>
| 기능 | 스크린샷 |
| --- | --- |
| gif |  |
<br/>
<br/>
=> Fix : subtodo post 리스트 형식으로 변경
